# Bank Customer Churn Prediction

## Data Loading and Initial Overview

In [12]:
from pathlib import Path

file_name = "Clasification_Model_Dataset.csv"
data_path = next(path for path in [Path.cwd() / "data" / "raw" / file_name, Path.cwd().parent / "data" / "raw" / file_name] if path.exists())
df = pd.read_csv(data_path)

df.head()

,Unnamed: 0,X,numero_de_cliente,cliente_vip,internet,cliente_edad,cliente_antiguedad,mrentabilidad,mrentabilidad_anual,mcomisiones,mactivos_margen,mpasivos_margen,cant_total_prod,tpaquete1,tpaquete2,tpaquete3,tpaquete4,tpaquete5,tpaquete6,tpaquete7,tpaquete8,tpaquete9,tcuentas,mdescubierto_preacordado,mcuentas_saldo,ctarjeta_debito_transacciones,mautoservicio,ctarjeta_visa,ctarjeta_visa_transacciones,mtarjeta_visa_consumo,ctarjeta_master,ctarjeta_master_transacciones,mtarjeta_master_consumo,cprestamos_personales,mprestamos_personales,cplazo_fijo,mplazo_fijo_dolares,mplazo_fijo_pesos,cfondos_comunes_inversion,mfondos_comunes_inversion_pesos,mfondos_comunes_inversion_dolares,Ctitulos,mtitulos,cseguro_auto,cseguro_vivienda,cseguro_accidentes_personales,ccaja_seguridad,mbonos_corporativos,mmonedas_extranjeras,minversiones_otras,cplan_sueldo,mplan_sueldo,mplan_sueldo_manual,cplan_sueldo_transaccion,ccuenta_debitos_automaticos,mcuenta_debitos_automaticos,ctarjeta_visa_debitos_automaticos,mttarjeta_visa_debitos_automaticos,cpagodeservicios,mpagodeservicios,cpagomiscuentas,mpagomiscuentas,mcomisiones_mantenimiento,ccomisiones_otras,mcomisiones_otras,ccambio_monedas,ccambio_monedas_compra,mcambio_monedas_compra,ccambio_monedas_venta,mcambio_monedas_venta,ctransferencias_recibidas,mtransferencias_recibidas,ctransferencias_emitidas,mtransferencias_emitidas,cextraccion_autoservicio,mextraccion_autoservicio,ccheques_depositados,mcheques_depositados,ccheques_emitidos,mcheques_emitidos,ccheques_depositados_rechazados,mcheques_depositados_rechazados,ccheques_emitidos_rechazados,mcheques_emitidos_rechazados,thomebanking,chomebanking_transacciones,cautoservicio,cautoservicio_transacciones,tmovimientos_ultimos90dias,Visa_marca_atraso,Visa_cuenta_estado,Visa_mfinanciacion_limite,Visa_msaldototal,Visa_msaldopesos,Visa_msaldodolares,Visa_mconsumospesos,Visa_mconsumosdolares,Visa_mlimitecompra,Visa_mpagado,Visa_mpagospesos,Visa_mpagosdolares,Visa_fechaalta,Visa_mconsumototal,Visa_cconsumos,Visa_mpagominimo,clase_binaria
0,0,1,4566150,0,1,44,72,3296.69,14455.27,579.66,910.65,1411.60,11,1,0,0,0,0,0,0,0,0,1,1.17,-460.04,2,2574.00,1,17,19451.75,1,18,17091.34,3,73704.79,0,0.0,0.0,0,0.0,0.0,0,0.00,0,1,0,0,0,0,0,1,56580.03,0.0,0,1,68.94,0,0.0,0,0.00,0,0.0,0.00,14,579.66,0,0,0.0,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,0,116,0.0,10.0,63180.0,29994.31,32262.86,2830.47,14555.47,59.47,70200.0,0.0,-19632.60,0.00,20130520.0,14555.47,13.0,3837.6,CONTINUA
1,1,2,4566430,0,0,78,159,1032.18,10141.18,790.58,71.21,135.29,6,1,0,0,0,0,0,0,0,0,1,1.17,6301.72,0,0.00,1,1,174.33,1,0,0.00,0,0.00,0,0.0,0.0,0,0.0,0.0,0,0.00,0,0,0,0,0,0,0,0,0.00,0.0,0,0,0.00,0,0.0,0,0.00,0,0.0,833.97,4,790.58,0,0,0.0,0,0.0,0,0.0,1,351.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,1,0,0,17,0.0,10.0,63180.0,182.45,213.46,0.00,-11.55,4.22,70200.0,0.0,-2976.51,62.78,20060210.0,-11.55,2.0,35.1,CONTINUA
2,2,3,4566445,0,1,64,299,-52.34,4752.64,236.08,-422.18,175.66,7,1,0,0,0,0,0,0,0,0,1,1.17,45.63,0,0.00,1,8,11670.93,1,0,0.00,0,0.00,0,0.0,0.0,0,0.0,0.0,0,0.00,0,0,0,0,0,0,0,0,0.00,0.0,0,0,0.00,0,0.0,0,0.00,0,0.0,0.00,6,236.08,0,0,0.0,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,0,0,0,10,0.0,10.0,176904.0,10367.71,12130.22,0.00,6788.67,0.00,196560.0,0.0,-12753.00,0.00,19960826.0,6788.67,4.0,1977.3,CONTINUA
3,3,4,4566621,0,1,48,282,485.91,10676.87,1280.47,-1275.18,596.07,8,1,0,0,0,0,0,0,0,0,1,1.17,5429.85,4,4103.69,1,9,9840.21,1,14,12383.23,0,0.00,0,0.0,0.0,0,0.0,0.0,3,10509.33,0,0,0,0,0,0,0,0,0.00,0.0,0,4,5303.31,0,0.0,0,0.00,2,2460.0,833.97,18,1280.47,0,0,0.0,0,0.0,0,0.0,0,0.00,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1,78,0,0,85,0.0,10.0,176904.0,6754.10,7433.72,468.57,2946.70,10.51,196560.0,0.0,-3685.76,0.00,20150204.0,2946.70,5.0,573.3,CONTINUA
4,5,6,4566907,0,1,45,171,5878.27,24298.75,64.38,22.11,4947.03,9,1,0,0,0,0,0,0,0,0,1,1.17,563006.87,10,4313.45,1,2,1496.03,1,0,0.00,0,0.00,1,351000.0,0.0,0,0.0,0.0,0,0.00,0,0,0,0,0,0,0,0,0.00,0.0,0,0,0.00,0,0.0,7,2171.89,1,339.3,0.00,12,64.38,0,0,0.0,0,0.0,0,0.0,2,16160.54,5,4797.0,0,0.0,0,0.0,0,0.0,0,0.0,1,4,0,0,94,0.0,10.0,44226.0,1316.65,1540.48,0.00,1048.32,0.00,49140.0,0.0,-1861.64,0.00,20050203.0,1048.32,1.0,128.7,CONTINUA

### Dimensiones y columnas

In [4]:
print(f'Filas: {df.shape[0]:,}'); print(f'Columnas: {df.shape[1]}'); print('\nPrimeras 20 columnas:'); print(df.columns.tolist()[:20])

Filas: 170,722
Columnas: 106

Primeras 20 columnas:
['Unnamed: 0', 'X', 'numero_de_cliente', 'cliente_vip', 'internet', 'cliente_edad', 'cliente_antiguedad', 'mrentabilidad', 'mrentabilidad_anual', 'mcomisiones', 'mactivos_margen', 'mpasivos_margen', 'cant_total_prod', 'tpaquete1', 'tpaquete2', 'tpaquete3', 'tpaquete4', 'tpaquete5', 'tpaquete6', 'tpaquete7']

## Exploratory Data Analysis - Variable objetivo y desbalance

In [ ]:
Before training a model, we examine whether the target variable is balanced. This helps determine whether accuracy alone will be a reliable evaluation metric.
##ES: 
Antes de entrenar los modelos, revisé cuántos clientes se dan de baja y cuántos continúan para saber si las clases están balanceadas.

In [5]:
resumen_target = df['clase_binaria'].value_counts(dropna=False).rename_axis('Clase').reset_index(name='Cantidad'); resumen_target['Porcentaje'] = resumen_target['Cantidad'] / len(df) * 100; resumen_target

      Clase  Cantidad  Porcentaje
0  CONTINUA    168887   98.925153
1      BAJA      1835    1.074847

In [ ]:
The dataset shows class imbalance. Therefore, ROC-AUC will be considered. 
##ES:
El conjunto de datos tiene más clientes que continúan que clientes que se dan de baja. Por eso voy a usar ROC-AUC (ROC-AUC es una métrica para evaluar modelos de clasificación, especialmente útil cuando las clases están desbalanceadas).

### Data Types and Missing Values / Tipos de datos y valores faltantes

In [6]:
resumen_columnas = pd.DataFrame({'tipo_de_dato': df.dtypes.astype(str), 'nulos': df.isna().sum(), 'porcentaje_nulos': (df.isna().mean() * 100).round(2), 'valores_unicos': df.nunique(dropna=False)}).sort_values('porcentaje_nulos', ascending=False); resumen_columnas.head(20)

,tipo_de_dato,nulos,porcentaje_nulos,valores_unicos
Visa_cconsumos,float64,21503,12.60,169
Visa_mconsumototal,float64,21503,12.60,126954
Visa_mconsumospesos,float64,21503,12.60,126954
Visa_mconsumosdolares,float64,21503,12.60,18253
Visa_mpagospesos,float64,21503,12.60,120000
Visa_mpagosdolares,float64,21503,12.60,12041
Visa_msaldodolares,float64,6101,3.57,19762
Visa_mlimitecompra,float64,6101,3.57,122
Visa_marca_atraso,float64,6101,3.57,3
Visa_mpagominimo,float64,6101,3.57,4308
Visa_mfinanciacion_limite,float64,6101,3.57,189
Visa_cuenta_estado,float64,6101,3.57,5
Visa_mpagado,float64,6101,3.57,12824
Visa_fechaalta,float64,6101,3.57,6237
Visa_msaldopesos,float64,6101,3.57,143235
Visa_msaldototal,float64,6101,3.57,143884
tpaquete4,int64,0,0.00,1
tpaquete5,int64,0,0.00,1
tpaquete6,int64,0,0.00,1
tpaquete7,int64,0,0.00,2

In [ ]:
This step examines columns that may contain unique identifiers rather than meaningful predictive information. These variables are not expected to help predict customer churn and may introduce noise into the model.
##ES:
En este paso revisé las columnas que pueden ser identificadores únicos de cada cliente. Estas columnas no aportan información útil para predecir si un cliente se dará de baja, por lo que podrían generar ruido en el modelo.

In [7]:
columnas_id = ['Unnamed: 0', 'X', 'numero_de_cliente']

resumen_ids = pd.DataFrame({
    'columna': columnas_id,
    'valores_unicos': [df[col].nunique() for col in columnas_id],
    'filas_totales': len(df)
})

resumen_ids

             columna  valores_unicos  filas_totales
0         Unnamed: 0          170722         170722
1                  X          170722         170722
2  numero_de_cliente          170722         170722

In [ ]:
The columns `Unnamed: 0`, `X`, and `numero_de_cliente` contain unique values, so they will be excluded from the modeling dataset.

In [ ]:
This step checks for columns with only one unique value across the entire dataset. Constant columns do not provide useful information for predicting customer churn, so they can be removed before modeling.
##ES:
En este paso revisé si hay columnas con un solo valor para todos los clientes. Estas columnas tampoco ayudan a predecir la baja de un cliente.

In [10]:
constant_columns = [
    column for column in df.columns
    if df[column].nunique(dropna=False) <= 1
]

print(f'Number of constant columns: {len(constant_columns)}')

constant_columns

Number of constant columns: 12

['tpaquete1',
 'tpaquete2',
 'tpaquete3',
 'tpaquete4',
 'tpaquete5',
 'tpaquete6',
 'tpaquete8',
 'mbonos_corporativos',
 'mmonedas_extranjeras',
 'minversiones_otras',
 'cautoservicio',
 'cautoservicio_transacciones']

In [9]:
columnas_con_nulos = resumen_columnas[
    resumen_columnas['nulos'] > 0
]

columnas_con_nulos

,tipo_de_dato,nulos,porcentaje_nulos,valores_unicos
Visa_cconsumos,float64,21503,12.60,169
Visa_mconsumototal,float64,21503,12.60,126954
Visa_mconsumospesos,float64,21503,12.60,126954
Visa_mconsumosdolares,float64,21503,12.60,18253
Visa_mpagospesos,float64,21503,12.60,120000
Visa_mpagosdolares,float64,21503,12.60,12041
Visa_msaldodolares,float64,6101,3.57,19762
Visa_mlimitecompra,float64,6101,3.57,122
Visa_marca_atraso,float64,6101,3.57,3
Visa_mpagominimo,float64,6101,3.57,4308
Visa_mfinanciacion_limite,float64,6101,3.57,189
Visa_cuenta_estado,float64,6101,3.57,5
Visa_mpagado,float64,6101,3.57,12824
Visa_fechaalta,float64,6101,3.57,6237
Visa_msaldopesos,float64,6101,3.57,143235
Visa_msaldototal,float64,6101,3.57,143884

In [10]:
pd.crosstab(
    df['ctarjeta_visa'],
    df['Visa_cconsumos'].isna(),
    margins=True
)

Visa_cconsumos   False   True     All
ctarjeta_visa
0                  882   6220    7102
1               145551  15191  160742
2                 2753     91    2844
3                   33      1      34
All             149219  21503  170722

In [17]:
analisis_nulos_visa = (
    df.assign(Visa_cconsumos_nulo=df['Visa_cconsumos'].isna())
      .groupby('Visa_cconsumos_nulo')
      .agg(
          clientes=('clase_binaria', 'size'),
          bajas=('clase_binaria', lambda x: (x == 'BAJA').sum()),
          tasa_baja=('clase_binaria', lambda x: (x == 'BAJA').mean())
      )
)

analisis_nulos_visa['tasa_baja'] = (
    analisis_nulos_visa['tasa_baja'] * 100
).round(3)

analisis_nulos_visa

C:\Users\pilar\AppData\Local\Temp\ipykernel_23824\2639771945.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(Visa_cconsumos_nulo=df['Visa_cconsumos'].isna())

                     clientes  bajas  tasa_baja
Visa_cconsumos_nulo
False                  149219    959      0.643
True                    21503    876      4.074

In [12]:
duplicados = df.duplicated().sum()

print(f'Filas duplicadas exactas: {duplicados}')

Filas duplicadas exactas: 0

In [13]:
columnas_a_eliminar = [
    'Unnamed: 0',
    'X',
    'numero_de_cliente'
] + columnas_constantes

X = df.drop(columns=columnas_a_eliminar + ['clase_binaria'])

# BAJA será 1: la clase que queremos detectar.
# CONTINUA será 0.
y = (df['clase_binaria'] == 'BAJA').astype(int)

print(f'Cantidad de variables predictoras: {X.shape[1]}')
print(f'Filas en X: {X.shape[0]}')
print('\nDistribución de la variable objetivo:')
print(y.value_counts())

Cantidad de variables predictoras: 90
Filas en X: 170722

Distribución de la variable objetivo:
clase_binaria
0    168887
1      1835
Name: count, dtype: int64

In [ ]:
## Train-Test Split

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print('Entrenamiento:', X_train.shape)
print('Validación:', X_valid.shape)

print('\nPorcentaje de bajas:')
print(f'Train: {y_train.mean() * 100:.3f}%')
print(f'Validación: {y_valid.mean() * 100:.3f}%')

Entrenamiento: (136577, 90)
Validación: (34145, 90)

Porcentaje de bajas:
Train: 1.075%
Validación: 1.075%

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

modelo_base = Pipeline(steps=[
    (
        'imputacion',
        SimpleImputer(
            strategy='median',
            add_indicator=True
        )
    ),
    ('escalado', StandardScaler()),
    (
        'modelo',
        LogisticRegression(
            class_weight='balanced',
            max_iter=2000,
            random_state=42
        )
    )
])

modelo_base.fit(X_train, y_train)

Pipeline(steps=[('imputacion',
                 SimpleImputer(add_indicator=True, strategy='median')),
                ('escalado', StandardScaler()),
                ('modelo',
                 LogisticRegression(class_weight='balanced', max_iter=2000,
                                    random_state=42))])